# Generated by Django 4.1.2 on 2022-10-11 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'productcategories',
            },
        ),
        migrations.CreateModel(
            name='ProductWrapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('old_Price', models.DecimalField(decimal_places=3, max_digits=7)),
                ('new_Price', models.DecimalField(decimal_places=3, max_digits=7)),
                ('tick_Presenter', models.CharField(default='Admin', max_length=255)),
                ('create_Date', models.DateTimeField(auto_now_add=True)),
                ('updated_Date', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255)),
                ('timer_ForSales', models.DateField()),
                ('location', models.TextField(blank=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productCreator', to=settings.AUTH_USER_MODEL)),
                ('location_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductLocation', to='store.locationcategory')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='store.productcategory')),
            ],
            options={
                'verbose_name_plural': 'ProductsWrapper',
                'ordering': ('-create_Date',),
            },
        ),
    ]
