# Generated by Django 4.1.2 on 2022-10-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productwrapper_is_in_besttickoftoday'),
    ]

    operations = [
        migrations.AddField(
            model_name='productwrapper',
            name='is_bestOfferOfWebsite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productwrapper',
            name='is_in_bestTickOfToday',
            field=models.BooleanField(default=False),
        ),
    ]
