# Generated by Django 4.1.2 on 2022-10-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productwrapper_is_entertainment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productwrapper',
            name='is_Entertainment',
        ),
        migrations.AddField(
            model_name='productwrapper',
            name='is_lastMinute',
            field=models.BooleanField(default=False),
        ),
    ]
