# Generated by Django 4.1.2 on 2022-10-20 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_productwrapper_is_entertainment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('product_Pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductPic', to='store.productwrapper')),
            ],
            options={
                'verbose_name_plural': 'imagealbum',
            },
        ),
    ]
