# Generated by Django 4.1.2 on 2022-10-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_imagealbum_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='imageAlbum',
        ),
    ]
