# Generated by Django 4.1.2 on 2022-10-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_delete_imagealbum'),
    ]

    operations = [
        migrations.AddField(
            model_name='productwrapper',
            name='link_Address',
            field=models.TextField(blank=True),
        ),
    ]
