# Generated by Django 4.1.2 on 2022-10-24 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_arttype_entertainmenttype_exercisetype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestaurantType',
            new_name='ProductType',
        ),
        migrations.DeleteModel(
            name='ArtType',
        ),
        migrations.DeleteModel(
            name='EntertainmentType',
        ),
        migrations.DeleteModel(
            name='ExerciseType',
        ),
    ]
