# Generated by Django 4.1.2 on 2022-10-24 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_producttype_typeofproducts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productwrapper',
            name='product_categorytype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='TypeOfProducts', to='store.typeofproducts'),
        ),
    ]
