# Generated by Django 4.1.2 on 2022-10-26 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_productwrapper_product_categorytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(default='kooft.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='productwrapper',
            name='product_categorytype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TypeOfProducts', to='store.typeofproducts'),
        ),
    ]
