# Generated by Django 4.1.2 on 2022-10-29 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_productcategory_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofproducts',
            name='product_Foreign',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='Product_SubCategory', to='store.productcategory'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
