# Generated by Django 4.1.2 on 2022-10-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_typeofproducts_product_foreign_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeofproducts',
            name='product_Foreign',
        ),
    ]
