# Generated by Django 4.1.2 on 2022-10-29 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_typeofproducts_product_foreign'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofproducts',
            name='product_Foreign',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='Product_SubCategory', to='store.productcategory'),
        ),
    ]
