# Generated by Django 4.1.2 on 2022-10-29 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_typeofproducts_product_foreign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeofproducts',
            name='product_Foreign',
        ),
    ]
