# Generated by Django 4.1.2 on 2022-10-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_typeofproducts_product_foreign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productwrapper',
            name='product_categorytype',
        ),
        migrations.DeleteModel(
            name='TypeOfProducts',
        ),
    ]
