# Generated by Django 4.1.2 on 2022-10-29 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_productwrapper_product_categorytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofproducts',
            name='product_MainCategoryKey',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='ProductSubCategory', to='store.productcategory'),
        ),
    ]
