# Generated by Django 4.1.2 on 2022-10-29 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_typeofproducts_product_maincategorykey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productwrapper',
            name='product_categorytype',
        ),
        migrations.RemoveField(
            model_name='typeofproducts',
            name='product_MainCategoryKey',
        ),
    ]
