# Generated by Django 4.1.2 on 2022-10-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_remove_productwrapper_product_categorytype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfProductsSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'TypeOfProducts',
            },
        ),
        migrations.DeleteModel(
            name='TypeOfProducts',
        ),
    ]
