# Generated by Django 4.1.2 on 2022-10-29 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_typeofproductssubcategory_delete_typeofproducts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeofproductssubcategory',
            options={'verbose_name_plural': 'TypeOfProductsSubCategory'},
        ),
    ]
