# Generated by Django 4.1.2 on 2022-10-29 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_typeofproductssubcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productwrapper',
            name='product_categorytype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TypeOfProductsSubCategory', to='store.typeofproductssubcategory'),
        ),
        migrations.AddField(
            model_name='typeofproductssubcategory',
            name='product_MainCategoryKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProductSubCategory', to='store.productcategory'),
        ),
    ]
