# Generated by Django 4.1.2 on 2022-10-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='mypic.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_types',
            field=models.CharField(choices=[('BA', 'Banner'), ('SL', 'Slider'), ('TC', 'Topcommercial'), ('TH', 'Tophit')], default='SL', max_length=2),
        ),
    ]
