# Generated by Django 4.1.2 on 2022-11-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_alter_image_image_alter_image_image_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productwrapper',
            name='product_category',
        ),
        migrations.AddField(
            model_name='productwrapper',
            name='product_category',
            field=models.ManyToManyField(related_name='Product', to='store.productcategory'),
        ),
    ]
