# Generated by Django 4.1.2 on 2022-11-14 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_remove_productwrapper_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productwrapper',
            name='product_category',
        ),
        migrations.AddField(
            model_name='productwrapper',
            name='product_category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='store.productcategory'),
        ),
    ]
