# Generated by Django 4.1.2 on 2022-12-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantityOfProduct',
            field=models.IntegerField(default=1),
        ),
    ]
